local library = loadstring(game:HttpGet("https://raw.githubusercontent.com/miroeramaa/TurtleLib/main/TurtleUiLib.lua"))()
local window = library:Window("Window")
window:Button("PlaceStartItems", function()
   loadstring(game:HttpGet(('https://raw.githubusercontent.com/Averymoistboi/Gasstationman/main/instaplace'),true))()
loadstring(game:HttpGet(('https://raw.githubusercontent.com/Averymoistboi/instaplaceBG/main/bocugs'),true))()
end)
window:Button("PlaceSurvival/carItems", function()
   loadstring(game:HttpGet(('https://raw.githubusercontent.com/Averymoistboi/InstaplaceACX/main/XCC'),true))()
end)
window:Button("PlaceNonStarterfoods", function()
   loadstring(game:HttpGet(('https://raw.githubusercontent.com/Averymoistboi/Fud/main/fud'),true))()
end)
window:Button("PlaceVeges/icecream", function()
   loadstring(game:HttpGet(('https://raw.githubusercontent.com/Averymoistboi/Ohgod/main/GOODGOD'),true))()
end)
